/**
 * Phase D -- Conversion fidelity tests.
 *
 * Verifies that gameToGraph() -> graphToGame() round-trip preserves all
 * properties for all 22 node types and all 8 edge types.
 *
 * Known asymmetries handled by normalizeGameJson():
 * - gameToGraph injects defaults: tags=[], activation_mode='automatic',
 *   pull_mode='pull_any', cooldown_time=null
 * - gameToGraph sets label = name ?? id; graphToGame strips label/nodeType
 * - Positions are generated by dagre (not compared)
 * - null/undefined optional edge fields are stripped
 * - If a node has no name, round-trip produces name = id
 */

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

import { graphToGame, gameToGraph } from '../conversion'
import type { GameDefinitionJSON } from '../conversion'

// ---------------------------------------------------------------------------
// Section A: Helpers
// ---------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

/** Resolve a path relative to the repo root (four levels up from __tests__). */
function fixturePath(...segments: string[]): string {
  return resolve(__dirname, '..', '..', '..', '..', ...segments)
}

function loadFixture(path: string): GameDefinitionJSON {
  return JSON.parse(readFileSync(path, 'utf-8')) as GameDefinitionJSON
}

const EDGE_OPTIONAL_KEYS = ['rate', 'formula', 'condition', 'target_property', 'modifier_mode'] as const

/**
 * Deep-clone and normalise a GameDefinitionJSON so that known round-trip
 * asymmetries are removed, making two sides comparable.
 */
function normalizeGameJson(game: GameDefinitionJSON): GameDefinitionJSON {
  const out: GameDefinitionJSON = JSON.parse(JSON.stringify(game))

  // Sort deterministically
  out.nodes.sort((a, b) => a.id.localeCompare(b.id))
  out.edges.sort((a, b) => a.id.localeCompare(b.id))

  for (const node of out.nodes) {
    const n = node as Record<string, unknown>

    // Inject base defaults that gameToGraph always adds
    if (!('tags' in n)) n.tags = []
    if (!('activation_mode' in n)) n.activation_mode = 'automatic'
    if (!('pull_mode' in n)) n.pull_mode = 'pull_any'
    if (!('cooldown_time' in n)) n.cooldown_time = null

    // gameToGraph sets label = name ?? id, then graphToGame copies name back.
    // If the original had no name, round-trip produces name = id.
    if (!('name' in n)) n.name = n.id

    // Strip editor-only keys that leak through the index signature
    delete n.label
    delete n.nodeType
  }

  for (const edge of out.edges) {
    const e = edge as Record<string, unknown>
    for (const key of EDGE_OPTIONAL_KEYS) {
      if (e[key] == null) delete e[key]
    }
  }

  return out
}

/** Full round-trip: game JSON -> graph -> game JSON. */
function roundTrip(game: GameDefinitionJSON): GameDefinitionJSON {
  const { nodes, edges } = gameToGraph(game)
  return graphToGame(nodes, edges, {
    name: game.name,
    description: game.description,
    stacking_groups: game.stacking_groups,
    time_unit: game.time_unit,
  })
}

/** Normalise both sides, compare with toEqual. */
function expectRoundTrip(game: GameDefinitionJSON): void {
  const result = roundTrip(game)
  expect(normalizeGameJson(result)).toEqual(normalizeGameJson(game))
}

/** Build a minimal game wrapping one node. */
function singleNodeGame(node: Record<string, unknown>): GameDefinitionJSON {
  return {
    schema_version: '1.0',
    name: 'Test',
    nodes: [node as GameDefinitionJSON['nodes'][0]],
    edges: [],
    stacking_groups: {},
  }
}

/** Build a game with two nodes and one edge between them. */
function twoNodeEdgeGame(
  edgeFields: Omit<GameDefinitionJSON['edges'][0], 'source' | 'target'> & { source?: string; target?: string },
): GameDefinitionJSON {
  return {
    schema_version: '1.0',
    name: 'Test',
    nodes: [
      { id: 'n1', type: 'resource', name: 'N1', initial_value: 0 },
      { id: 'n2', type: 'generator', name: 'N2', base_production: 1, cost_base: 10, cost_growth_rate: 1.07, cycle_time: 1 },
    ],
    edges: [{ source: 'n2', target: 'n1', ...edgeFields } as GameDefinitionJSON['edges'][0]],
    stacking_groups: {},
  }
}

// ---------------------------------------------------------------------------
// Section B: Metadata round-trip
// ---------------------------------------------------------------------------

describe('Metadata round-trip', () => {
  it('preserves name, description, stacking_groups, time_unit', () => {
    const game: GameDefinitionJSON = {
      schema_version: '1.0',
      name: 'Full Meta',
      description: 'A description',
      stacking_groups: { grp1: 'multiplicative', grp2: 'additive' },
      time_unit: 'seconds',
      nodes: [{ id: 'r1', type: 'resource', name: 'R1', initial_value: 0 }],
      edges: [],
    }
    const result = roundTrip(game)
    expect(result.name).toBe('Full Meta')
    expect(result.description).toBe('A description')
    expect(result.stacking_groups).toEqual({ grp1: 'multiplicative', grp2: 'additive' })
    expect(result.time_unit).toBe('seconds')
  })

  it('preserves schema_version', () => {
    const game: GameDefinitionJSON = {
      schema_version: '1.0',
      name: 'SV Test',
      nodes: [],
      edges: [],
      stacking_groups: {},
    }
    expect(roundTrip(game).schema_version).toBe('1.0')
  })

  it('handles absent optional fields', () => {
    const game: GameDefinitionJSON = {
      schema_version: '1.0',
      name: 'Minimal',
      nodes: [],
      edges: [],
      stacking_groups: {},
    }
    const result = roundTrip(game)
    expect(result.description).toBeUndefined()
    expect(result.time_unit).toBeUndefined()
  })
})

// ---------------------------------------------------------------------------
// Section C: Per-fixture round-trip
// ---------------------------------------------------------------------------

const FIXTURE_PATHS: [string, string][] = [
  ['minicap', 'tests/fixtures/minicap.json'],
  ['mediumcap', 'tests/fixtures/mediumcap.json'],
  ['cookie_clicker', 'tests/fixtures/e2e/cookie_clicker.json'],
  ['factory_idle', 'tests/fixtures/e2e/factory_idle.json'],
  ['prestige_tower', 'tests/fixtures/e2e/prestige_tower.json'],
  ['speed_runner', 'tests/fixtures/e2e/speed_runner.json'],
  ['full_kitchen', 'tests/fixtures/e2e/full_kitchen.json'],
]

describe('Per-fixture round-trip', () => {
  for (const [label, relPath] of FIXTURE_PATHS) {
    it(`round-trips ${label}`, () => {
      const game = loadFixture(fixturePath(relPath))
      expectRoundTrip(game)
    })
  }
})

// ---------------------------------------------------------------------------
// Section D: Per-node-type coverage (22 types + 1 defaults-only sweep)
// ---------------------------------------------------------------------------

describe('Per-node-type round-trip', () => {
  it('round-trips resource with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'resource', name: 'Test Node', initial_value: 500,
    }))
  })

  it('round-trips generator with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'generator', name: 'Test Node',
      base_production: 5, cost_base: 25, cost_growth_rate: 1.2, cycle_time: 2,
    }))
  })

  it('round-trips nested_generator with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'nested_generator', name: 'Test Node',
      target_generator: 'gen1', production_rate: 3, cost_base: 200, cost_growth_rate: 1.3,
    }))
  })

  it('round-trips upgrade with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'upgrade', name: 'Test Node',
      upgrade_type: 'additive', magnitude: 50, cost: 500, target: 'gen1',
      stacking_group: 'grp1', duration: 30,
    }))
  })

  it('round-trips prestige_layer with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'prestige_layer', name: 'Test Node',
      formula_expr: 'floor(x/1e6)', layer_index: 2, reset_scope: ['gen1'],
      persistence_scope: ['upg1'], bonus_type: 'additive',
    }))
  })

  it('round-trips sacrifice with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'sacrifice', name: 'Test Node',
      formula_expr: 'log(x)', reset_scope: ['gen1'], bonus_type: 'percentage',
    }))
  })

  it('round-trips achievement with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'achievement', name: 'Test Node',
      condition_type: 'multi_threshold',
      targets: [{ node_id: 'r1', property: 'balance', threshold: 100 }],
      logic: 'or', bonus: { type: 'multiplier', value: 2 }, permanent: false,
    }))
  })

  it('round-trips manager with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'manager', name: 'Test Node',
      target: 'gen1', automation_type: 'buy',
    }))
  })

  it('round-trips converter with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'converter', name: 'Test Node',
      inputs: [{ resource: 'r1', amount: 5 }],
      outputs: [{ resource: 'r2', amount: 1 }],
      rate: 2,
    }))
  })

  it('round-trips probability with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'probability', name: 'Test Node',
      expected_value: 1.5, variance: 0.3, crit_chance: 0.1, crit_multiplier: 3,
    }))
  })

  it('round-trips end_condition with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'end_condition', name: 'Test Node',
      condition_type: 'multi_threshold',
      targets: [{ node_id: 'r1', property: 'balance', threshold: 1000 }],
      logic: 'or',
    }))
  })

  it('round-trips unlock_gate with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'unlock_gate', name: 'Test Node',
      condition_type: 'multi_threshold',
      targets: [{ node_id: 'r1', property: 'balance', threshold: 50 }],
      prerequisites: ['ach1'], logic: 'and', permanent: false,
    }))
  })

  it('round-trips choice_group with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'choice_group', name: 'Test Node',
      options: ['a', 'b', 'c'], max_selections: 2, respeccable: true, respec_cost: 100,
    }))
  })

  it('round-trips register with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'register', name: 'Test Node',
      formula_expr: 'a + b * 2', input_labels: [{ a: 'Input A' }],
    }))
  })

  it('round-trips gate with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'gate', name: 'Test Node',
      mode: 'probabilistic', weights: [1, 2], probabilities: [0.3, 0.7],
    }))
  })

  it('round-trips queue with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'queue', name: 'Test Node',
      delay: 5, capacity: 10,
    }))
  })

  it('round-trips tickspeed with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'tickspeed', name: 'Test Node',
      base_tickspeed: 2,
    }))
  })

  it('round-trips autobuyer with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'autobuyer', name: 'Test Node',
      target: 'gen1', interval: 5, priority: 3, condition: 'x > 100',
      bulk_amount: '10', enabled: false,
    }))
  })

  it('round-trips drain with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'drain', name: 'Test Node',
      rate: 3, condition: 'x > 0',
    }))
  })

  it('round-trips buff with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'buff', name: 'Test Node',
      buff_type: 'proc', duration: 20, proc_chance: 0.15, multiplier: 3,
      target: 'gen1', cooldown: 5,
    }))
  })

  it('round-trips synergy with non-default values', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'synergy', name: 'Test Node',
      sources: ['gen1', 'gen2'], formula_expr: 'a * b', target: 'gen1',
    }))
  })

  it('round-trips all node types with only default values', () => {
    const types = [
      'resource', 'generator', 'nested_generator', 'upgrade', 'prestige_layer',
      'sacrifice', 'achievement', 'manager', 'converter', 'probability',
      'end_condition', 'unlock_gate', 'choice_group', 'register', 'gate',
      'queue', 'tickspeed', 'autobuyer', 'drain', 'buff', 'synergy',
    ]
    for (const t of types) {
      const game = singleNodeGame({ id: `${t}-node`, type: t, name: `${t} Node` })
      expectRoundTrip(game)
    }
  })
})

// ---------------------------------------------------------------------------
// Section E: Per-edge-type coverage
// ---------------------------------------------------------------------------

describe('Per-edge-type round-trip', () => {
  it('round-trips resource_flow edge', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'resource_flow' }))
  })

  it('round-trips consumption edge', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'consumption' }))
  })

  it('round-trips production_target edge', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'production_target' }))
  })

  it('round-trips state_modifier edge', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'state_modifier' }))
  })

  it('round-trips activator edge', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'activator' }))
  })

  it('round-trips trigger edge', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'trigger' }))
  })

  it('round-trips unlock_dependency edge', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'unlock_dependency' }))
  })

  it('round-trips upgrade_target edge', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'upgrade_target' }))
  })

  it('round-trips state_modifier with modifier_mode set and target_property', () => {
    expectRoundTrip(twoNodeEdgeGame({
      id: 'e1', edge_type: 'state_modifier',
      modifier_mode: 'set', target_property: 'base_production',
    }))
  })

  it('round-trips state_modifier with modifier_mode add', () => {
    expectRoundTrip(twoNodeEdgeGame({
      id: 'e1', edge_type: 'state_modifier', modifier_mode: 'add',
    }))
  })

  it('round-trips state_modifier with modifier_mode multiply', () => {
    expectRoundTrip(twoNodeEdgeGame({
      id: 'e1', edge_type: 'state_modifier', modifier_mode: 'multiply',
    }))
  })

  it('round-trips edge with formula and condition', () => {
    expectRoundTrip(twoNodeEdgeGame({
      id: 'e1', edge_type: 'resource_flow',
      rate: 5, formula: 'x * 2', condition: 'x > 0',
    }))
  })
})

// ---------------------------------------------------------------------------
// Section F: Edge cases
// ---------------------------------------------------------------------------

describe('Edge cases', () => {
  it('round-trips empty game (0 nodes, 0 edges)', () => {
    expectRoundTrip({
      schema_version: '1.0',
      name: 'Empty',
      nodes: [],
      edges: [],
      stacking_groups: {},
    })
  })

  it('round-trips node with activation_mode interactive and tags', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'resource', name: 'Test Node',
      initial_value: 0, activation_mode: 'interactive', tags: ['paid'],
    }))
  })

  it('round-trips node with explicit null optional fields', () => {
    expectRoundTrip(singleNodeGame({
      id: 'test-node', type: 'resource', name: 'Test Node',
      initial_value: 0, cooldown_time: null,
    }))
  })

  it('round-trips edge with rate 0 (falsy but valid)', () => {
    expectRoundTrip(twoNodeEdgeGame({ id: 'e1', edge_type: 'resource_flow', rate: 0 }))
  })
})
